language: node_js
node_js:
  - "12"
dist: trusty
sudo: false

branches:
  only:
  - master

cache:
  directories:
    - node_modules

script:
  - npm run lint
  - npm run build-ci
  - mv dist/timer/index.html dist/timer/404.html

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/timer
  on:
    branch: master
